# Generated by Django 6.0.1 on 2026-03-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='abn',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
