"""
Django settings for melbourn project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
from django.utils.log import DEFAULT_LOGGING

from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

GOOGLE_MAPS_API_KEY = os.environ.get('GOOGLE_MAPS_API_KEY','') 
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY','')
STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY','') 
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET','')
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY','somethinvcjvflvdhxbvvvccvvvvvbbvsfypb jobdtuvxfghn')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = [
#     'localhost',
#     'mcl-1fpe.onrender.com',
#     'triple-solely-entrepreneur-ski.trycloudflare.com/'
# ]
# 
ALLOWED_HOSTS = [
    'sevenstarlimo.com.au',
    'www.sevenstarlimo.com.au'
]
CSRF_TRUSTED_ORIGINS = [
    'https://sevenstarlimo.com.au',
    'https://www.sevenstarlimo.com.au',
]

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # my apps 
    'anymail',
    'pwa',
    'core',
    'orders',
    'accounts',
    'tours'
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'melbourn.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.context_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'melbourn.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASE_URL = os.environ.get('DATABASE_URL')
if DATABASE_URL:
    import dj_database_url
    DATABASES = {'default': dj_database_url.parse(DATABASE_URL)}
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'
LOGGING = DEFAULT_LOGGING


#WhiteNoise caching
if DEBUG : 
  WHITENOISE_MAX_AGE = 0  # DEVOLOPMENT
else :
  WHITENOISE_MAX_AGE = 31536000 # production : 1 year
  CSRF_COOKIE_SECURE = True
  SESSION_COOKIE_SECURE = True
  SECURE_SSL_REDIRECT = True  # If using HTTPS
  SECURE_HSTS_SECONDS = 31536000  # 1 year
  SECURE_HSTS_INCLUDE_SUBDOMAINS = True
  SECURE_HSTS_PRELOAD = True
  SECURE_BROWSER_XSS_FILTER = True
  SECURE_CONTENT_TYPE_NOSNIFF = True
  X_FRAME_OPTIONS = "DENY"




# Admin panel
JAZZMIN_SETTINGS = {
    'site_title': 'SevenStar Admin',
    'site_header': 'SevenStar Admin',
    "site_brand": "SevenStar", 
    'site_logo': 'img/logo.png',
    'welcome_sign': 'Manage The Web',
    #"custom_css": "admin/admin.css",  
    #"custom_js": "admin/admin.js", 
    "show_sidebar": True,
}

PWA_APP_NAME = 'SevenStar'
PWA_APP_DESCRIPTION = "SevenStar"
PWA_APP_THEME_COLOR = '#0A0302'
PWA_APP_BACKGROUND_COLOR = '#ffffff'
PWA_APP_DISPLAY = 'standalone'
PWA_APP_SCOPE = '/'
PWA_APP_ORIENTATION = 'any'
PWA_APP_START_URL = '/'
PWA_APP_STATUS_BAR_COLOR = 'default'
PWA_APP_ICONS = [
    {
        'src': '/static/img/logo.png',
        'sizes': '160x160'
    }
]
PWA_APP_ICONS_APPLE = [
    {
        'src': '/static/img/logo.png',
        'sizes': '160x160'
    }
]
PWA_APP_SPLASH_SCREEN = [
    {
        'src': '/static/img/logo.png',
        'media': '(device-width: 320px) and (device-height: 568px) and (-webkit-device-pixel-ratio: 2)'
    }
]
PWA_APP_DIR = 'ltr'
PWA_APP_LANG = 'en-US'
PWA_APP_SHORTCUTS = []
PWA_APP_SCREENSHOTS = [
    {
      'src': '/static/img/logo.png',
      'sizes': '750x1334',
      "type": "image/png"
    }
]

PWA_SERVICE_WORKER_PATH = BASE_DIR / 'sw.js'

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com' 
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER','')
# EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD','')
# DEFAULT_FROM_EMAIL = ' SevenStar Limo <management@sevenstarlimo.com.au>'
# 
EMAIL_BACKEND = "anymail.backends.resend.EmailBackend"

ANYMAIL = {
    "RESEND_API_KEY": os.environ.get('RESEND_API_KEY',''),
}
DEFAULT_FROM_EMAIL = "SevenStar Management <management@sevenstarlimo.com.au>"
SERVER_EMAIL = "server@sevenstarlimo.com.au"
ADMIN_NAME = os.environ.get('ADMIN_NAME')
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL')
ADMINS = [
    (ADMIN_NAME, ADMIN_EMAIL),
]
