# Generated by Django 6.0.1 on 2026-04-01 02:47

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(choices=[('yarra_valley', 'Yarra Valley Wine Tours'), ('mornington', 'Mornington Peninsula Wine Tours'), ('great_ocean_road', 'Great Ocean Road Tours'), ('victorian_winery', 'Victorian Winery Tours'), ('golf', 'Golf Tours'), ('melbourne_victorian', 'Melbourne and Victorian Tours'), ('grampians', 'Grampians Tours'), ('peninsula_hot_springs', 'Peninsula Hot Springs Tours'), ('fruit_picking', 'Fruit Picking Tours'), ('victorian_ski', 'Victorian Ski Tours')], max_length=30, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=250.0, help_text='Price per booking (AUD). Stripe 3% fee is added on top.', max_digits=10)),
                ('price_note', models.CharField(blank=True, help_text="Optional note shown to customer, e.g. 'per person' or 'per group up to 7'.", max_length=200)),
            ],
            options={
                'verbose_name': 'Tour Price',
                'verbose_name_plural': 'Tour Prices',
                'ordering': ['tour_type'],
            },
        ),
        migrations.CreateModel(
            name='TourBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tour_type', models.CharField(choices=[('yarra_valley', 'Yarra Valley Wine Tours'), ('mornington', 'Mornington Peninsula Wine Tours'), ('great_ocean_road', 'Great Ocean Road Tours'), ('victorian_winery', 'Victorian Winery Tours'), ('golf', 'Golf Tours'), ('melbourne_victorian', 'Melbourne and Victorian Tours'), ('grampians', 'Grampians Tours'), ('peninsula_hot_springs', 'Peninsula Hot Springs Tours'), ('fruit_picking', 'Fruit Picking Tours'), ('victorian_ski', 'Victorian Ski Tours')], default='yarra_valley', max_length=30)),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_number', models.CharField(max_length=30)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('number_of_passengers', models.IntegerField(default=2)),
                ('number_of_bags', models.IntegerField(default=2)),
                ('pickup_address', models.CharField(max_length=500)),
                ('booking_date', models.DateField(default=datetime.date.today)),
                ('booking_time', models.TimeField(default=django.utils.timezone.now)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paid', models.BooleanField(default=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
