# Generated by Django 6.0.1 on 2026-04-01 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TourCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Mercedes S-Class', max_length=120)),
                ('description', models.CharField(blank=True, help_text='Short tagline shown on the card', max_length=255)),
                ('image', models.ImageField(blank=True, help_text='Car photo', null=True, upload_to='tour_cars/')),
                ('max_passengers', models.PositiveSmallIntegerField(default=4, help_text='Maximum passengers this vehicle seats')),
                ('display_order', models.PositiveSmallIntegerField(default=0, help_text='Lower = shown first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tour Vehicle',
                'verbose_name_plural': 'Tour Vehicles',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='TourPrice',
        ),
        migrations.AlterModelOptions(
            name='tourbooking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tour Inquiry', 'verbose_name_plural': 'Tour Inquiries'},
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='number_of_bags',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='stripe_payment_intent_id',
        ),
        migrations.RemoveField(
            model_name='tourbooking',
            name='total_price',
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='additional_stops',
            field=models.TextField(blank=True, help_text='Newline-separated additional stops'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='booking_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='booking_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='number_of_passengers',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='passenger_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='passenger_name',
            field=models.CharField(max_length=180),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='passenger_number',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='pickup_address',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='tour_type',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourbooking',
            name='selected_car',
            field=models.ForeignKey(blank=True, help_text='Vehicle chosen by the customer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tours.tourcar'),
        ),
    ]
