# Generated by Django 6.0.1 on 2026-04-05 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_tourcar_delete_tourprice_alter_tourbooking_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tourbooking',
            name='return_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='additional_stops',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='passenger_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='selected_car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tours.tourcar'),
        ),
        migrations.AlterField(
            model_name='tourbooking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourcar',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
