# Generated by Django 6.0.1 on 2026-02-20 04:19

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField()),
                ('passenger_number', models.CharField()),
                ('passenger_email', models.EmailField(max_length=254)),
                ('number_of_passengers', models.IntegerField(default=2)),
                ('number_of_bags', models.IntegerField(default=2)),
                ('pickup_address', models.CharField()),
                ('additional_stop', models.CharField(blank=True, null=True)),
                ('flight_number', models.CharField()),
                ('pickup_date', models.DateField(default=datetime.date.today)),
                ('pickup_time', models.TimeField(default=django.utils.timezone.now)),
                ('destination_address', models.CharField()),
                ('limo_service_type', models.CharField()),
                ('baby_seat', models.BooleanField(default=False)),
                ('return_ride', models.BooleanField(default=False)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('vehicle_colour', models.CharField(blank=True, null=True)),
                ('wedding_ribbon', models.CharField(blank=True, null=True)),
                ('special_signboard', models.CharField()),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name_on_card', models.CharField()),
                ('card_type', models.CharField()),
                ('card_number', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
