# Generated by Django 6.0.4 on 2026-04-13 07:19

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_discount', models.DecimalField(decimal_places=3, default=0.025, max_digits=7)),
                ('return_discount', models.DecimalField(decimal_places=3, default=0.05, max_digits=7)),
                ('extra_charge_for_down_hours', models.DecimalField(decimal_places=3, default=0.3, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sedan 1-5')),
                ('img_url', models.URLField(blank=True, null=True)),
                ('max_passangers', models.IntegerField(default=5)),
                ('max_bags', models.IntegerField(default=5)),
                ('base_price', models.DecimalField(decimal_places=2, default=30, max_digits=6)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=3.5, max_digits=6)),
                ('stop', models.DecimalField(decimal_places=2, default=15, max_digits=6)),
                ('oh_rate', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('remote_pickup_multiplier', models.DecimalField(decimal_places=10, default=1.0, help_text='Applied when pickup is >10 km from Melbourne CBD. E.g. 1.25 = 25% surcharge. Leave at 1.000 for no surcharge.', max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('ptp', 'Point to Point'), ('oh', 'Hourly / As Directed'), ('fair', 'From Airport'), ('tair', 'To Airport')], default='ptp', max_length=10)),
                ('passenger_name', models.CharField(max_length=200)),
                ('passenger_number', models.CharField(max_length=30)),
                ('passenger_email', models.EmailField(max_length=254)),
                ('number_of_passengers', models.IntegerField(default=2)),
                ('number_of_bags', models.IntegerField(default=2)),
                ('pickup_address', models.CharField(max_length=500)),
                ('destination_address', models.CharField(max_length=500)),
                ('additional_stop', models.CharField(blank=True, max_length=500, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=20)),
                ('pickup_date', models.DateField(default=datetime.date.today)),
                ('pickup_time', models.TimeField(default=django.utils.timezone.now)),
                ('hourly_hours', models.CharField(blank=True, help_text='Number of hours requested (hourly hire only)', max_length=20, null=True)),
                ('limo_service_type', models.CharField(max_length=50)),
                ('baby_seat', models.BooleanField(default=False)),
                ('number_of_babies', models.IntegerField(default=0)),
                ('baby_ages', models.CharField(blank=True, default='', help_text="Comma-separated ages, e.g. '7 months,2 years,1 year'", max_length=100)),
                ('return_ride', models.BooleanField(default=False)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('vehicle_colour', models.CharField(blank=True, max_length=30, null=True)),
                ('wedding_ribbon', models.CharField(blank=True, max_length=30, null=True)),
                ('special_signboard', models.CharField(blank=True, max_length=200)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paid', models.BooleanField(default=False)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=200)),
                ('driver_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('driver_name', models.CharField(blank=True, default='none', null=True)),
                ('driver_number', models.CharField(blank=True, default='none', null=True)),
                ('driver_email', models.CharField(blank=True, default='none', null=True)),
                ('driver_address', models.CharField(blank=True, default='none', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
