# Generated by Django 6.0.4 on 2026-04-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='details_for_driver',
            field=models.CharField(blank=True, default='none', null=True),
        ),
    ]
