# Generated by Django 6.0.1 on 2026-04-11 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_discount', models.DecimalField(decimal_places=3, default=0.025, max_digits=7)),
                ('return_discount', models.DecimalField(decimal_places=3, default=0.05, max_digits=7)),
                ('extra_charge_for_down_hours', models.DecimalField(decimal_places=3, default=0.3, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sedan 1-5')),
                ('img_url', models.URLField(blank=True, null=True)),
                ('max_passangers', models.IntegerField(default=5)),
                ('max_bags', models.IntegerField(default=5)),
                ('base_price', models.DecimalField(decimal_places=2, default=30, max_digits=6)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=3.5, max_digits=6)),
                ('stop', models.DecimalField(decimal_places=2, default=15, max_digits=6)),
                ('oh_rate', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
                ('remote_pickup_multiplier', models.DecimalField(decimal_places=10, default=1.0, help_text='Applied when pickup is >10 km from Melbourne CBD. E.g. 1.25 = 25% surcharge. Leave at 1.000 for no surcharge.', max_digits=15)),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_on_card',
        ),
        migrations.AddField(
            model_name='order',
            name='baby_ages',
            field=models.CharField(blank=True, default='', help_text="Comma-separated ages, e.g. '7 months,2 years,1 year'", max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='hourly_hours',
            field=models.CharField(blank=True, help_text='Number of hours requested (hourly hire only)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='number_of_babies',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('ptp', 'Point to Point'), ('oh', 'Hourly / As Directed'), ('fair', 'From Airport'), ('tair', 'To Airport')], default='ptp', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_stop',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='destination_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='flight_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='limo_service_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='passenger_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='passenger_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='special_signboard',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='vehicle_colour',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='wedding_ribbon',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
