# Generated by Django 6.0.4 on 2026-04-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_details_for_driver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='details_for_driver',
            field=models.CharField(blank=True, default='none'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_address',
            field=models.CharField(blank=True, default='none'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_email',
            field=models.CharField(blank=True, default='none'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, default='none'),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_number',
            field=models.CharField(blank=True, default='none'),
        ),
    ]
