# Generated by Django 6.0.1 on 2026-02-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_order_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('p2p', 'Point to Point'), ('h2h', 'Point to Point'), ('fair', 'From Airport'), ('tair', 'To Airport'), ('2h', '2 Hour Hire')], default='p2p', max_length=10),
        ),
    ]
