# Generated by Django 6.0.1 on 2026-02-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='card_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='order',
            name='name_on_card',
        ),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('ptp', 'Point to Point'), ('oh', '1 Hour / As Directed'), ('th', '2 Hour Hire'), ('fair', 'From Airport'), ('tair', 'To Airport')], default='ptp', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
