# Generated by Django 6.0.4 on 2026-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_details_for_driver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='details_for_driver',
            field=models.CharField(blank=True, default='none', max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_address',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_email',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=20, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_name',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='driver_number',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
    ]
