# Generated by Django 6.0.1 on 2026-03-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_card_number_remove_order_card_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('th_discount', models.DecimalField(decimal_places=2, default=0.025, max_digits=6)),
                ('return_discount', models.DecimalField(decimal_places=2, default=0.05, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Sedan 1-5')),
                ('max_passangers', models.IntegerField(default=5)),
                ('max_bags', models.IntegerField(default=5)),
                ('base_price', models.DecimalField(decimal_places=2, default=30, max_digits=6)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=3.5, max_digits=6)),
                ('stop', models.DecimalField(decimal_places=2, default=15, max_digits=6)),
                ('th_rate', models.DecimalField(decimal_places=2, default=200, max_digits=6)),
                ('oh_rate', models.DecimalField(decimal_places=2, default=100, max_digits=6)),
            ],
        ),
    ]
