# Generated by Django 6.0.1 on 2026-03-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_discount_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
