# Generated by Django 6.0.1 on 2026-03-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_driver_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='driver_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
