# Generated by Django 6.0.1 on 2026-03-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_order_driver_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='extra_charge_for_down_hours',
            field=models.DecimalField(decimal_places=3, default=0.3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='discount',
            name='return_discount',
            field=models.DecimalField(decimal_places=3, default=0.05, max_digits=7),
        ),
        migrations.AlterField(
            model_name='discount',
            name='th_discount',
            field=models.DecimalField(decimal_places=3, default=0.025, max_digits=7),
        ),
    ]
