# Generated by Django 6.0.1 on 2026-04-01 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_discount_extra_charge_for_down_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
