# Generated by Django 6.0.1 on 2026-04-05 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_rates_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rates',
            name='th_rate',
        ),
        migrations.AddField(
            model_name='order',
            name='hourly_hours',
            field=models.CharField(blank=True, help_text='Number of hours requested (hourly hire only)', max_length=20, null=True),
        ),
        # migrations.AddField(
#             model_name='rates',
#             name='remote_pickup_multiplier',
#             field=models.DecimalField(decimal_places=10, default=1.0, help_text='Applied when pickup is >10 km from Melbourne CBD. E.g. 1.25 = 25% surcharge. Leave at 1.000 for no surcharge.', max_digits=15),),
        migrations.AlterField(
            model_name='order',
            name='service_type',
            field=models.CharField(choices=[('ptp', 'Point to Point'), ('oh', 'Hourly / As Directed'), ('fair', 'From Airport'), ('tair', 'To Airport')], default='ptp', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
