# Generated by Django 6.0.1 on 2026-04-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_remove_rates_th_rate_order_hourly_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='remote_pickup_multiplier',
            field=models.DecimalField(decimal_places=10, default=1.0, help_text='Applied when pickup is >10 km from Melbourne CBD. E.g. 1.25 = 25% surcharge. Leave at 1.000 for no surcharge.', max_digits=15),
        ),
    ]
